### ISSUE TITLE
Movable.sed.url not working

### ISSUE THREAD

**Issue by ShinyZygarde44** [Jisagi/SeedminerGuide#24]
When I try to upload the movable.sed to the TADpole website, it is displayed as movable.sed.url even though it appears as movable.sed in File Explorer, and it tells me that the movable.sed size is not valid. I can’t seem to find anyone else with this problem, so I would really like to know what’s happening.

**Comment by Jisagi** [comment]
The issue tracker is not for geenral help. Please use the Nintendo Homebrew discord server for help.
